name: 'web_app'
mode: 'dev'
port: 8071
start_time: '2022-11-30'
machineID: 1
log:
  level: 'debug'
  filename: 'web_app.log'
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: mysql-test2
  port: 3306
  user: 'root'
  password: '123456'
  dbname: 'bbs'
  max_open_connection: 200
  max_idle_connection: 10
redis:
  host: redis-test2
  passowrd: ''
  port: 6379
  db: 0
  pool_size: 0
